### ISSUE TITLE
Preciso das fotos

### ISSUE THREAD

**Issue by fnknda** [JoaoFukuda/InterpretadorAsm#10]
Eu preciso das fotos da arquitetura que a gente combinou...

**Comment by 15483114** [comment]
eu mandei pelo telegram, vou pedir pra bia pq acho que ela passou a limpo

**Comment by fnknda** [comment]
Muito obrigado pela imagem, @lenkiro 
![image](https://user-images.githubusercontent.com/37672942/58654990-7d26cc00-82ef-11e9-9ed6-25c470cb4173.png)

**Comment by fnknda** [comment]
Agora acho que uma menos "suja" seria bom, mas da para trabalhar com isso

edit: Aquela que a gente fez com o prof em sala seria preferível

edit: Valeu, @15483114 
![image](https://user-images.githubusercontent.com/37672942/58655907-a21c3e80-82f1-11e9-85ba-7770c2641acd.png)
