### ISSUE TITLE
Como fazer o firmware

### ISSUE THREAD

**Issue by 15483114** [JoaoFukuda/InterpretadorAsm#11]
Acho que não entendi plenamente o firmware, mas acho que pensar em como montá-lo vai ajudar a conectar o trabalho. Estou com algumas dúvidas, coloquei o que eu acho que é para colocar em cada espaço
![image](https://user-images.githubusercontent.com/50025985/59165676-a3b9e380-8af5-11e9-9db2-ccef32c0ef41.png)

Internal CPU Control Signals: opcode traduzido (linha que o decodificardor seleciona baseado no opcode). Ou uma sequencia de estados especifica para a execução da instrução?
System
 Bus Control Signals: Sinais do barramento que indicam escrita ou leitura.Aqui que vão estar os números indicando as portinhas que estão abertas ou fechadas?
Jump Condition: sinal de que tem jump. No caso seriam só os comando do professor (quando tiver algum comando de JMP) ou tem alguns outro tipo?
Micro-instruction Address: seria onde está o opcode ou o proximo opcode?

**Comment by fnknda** [comment]
* Internal CPU Control Signal: São um monte de 0's e 1's que indicam o estado das portas na arquitetura (0 = fechada ou 1 = aberta). Aqui que vão estar os números indicando as portinhas que estão abertas ou fechadas.
* Bus Control Signals: Indicam os sinais que servem para somar, subtrair, dividir ou multiplicar, ler ou escrever. Sinais de controle.
* Jump Condition: Serve para ver se vai pular (caso chegue no final das execuções) e pula para outro ciclo (busca ou qqr outra coisa, sla).
* Micro-instruction Address: Onde o jump daqui de cima vai pular para

Esse jump serve para pular entre instruções do firmware e não meche com nada de fora.

**Comment by fnknda** [comment]
![image](https://user-images.githubusercontent.com/37672942/60569249-3f312380-9d45-11e9-9012-83769344404d.png)
