### ISSUE TITLE
O que colocar no GUI

### ISSUE THREAD

**Issue by fnknda** [JoaoFukuda/InterpretadorAsm#9]
Eu preciso saber o que precisa ter na interface gráfica para poder já começar

**Comment by lenkiro** [comment]
Hm não tenho certeza. Na minha cabeça era tipo algo parecido com o ketman, com os registradores e memória mostrando as mudanças em tempo real

**Comment by fnknda** [comment]
Mas tem que ver que parte da memória ele quer
Eu vou começar fazendo um ketman (com os registradores de fora e dentro da UC e o código do lado) e depois a gente ve essa parte da memória

**Comment by fnknda** [comment]
Precisa implementar:
- [x] Área para digitar
- [x] Registradores (ax, b,x, cx, dx, ir, pc)
- [x] Flags
- [ ] Memória
- [x] Linha atual
- [x] Tempo atual
- [x] Controles (rodar, desfazer, passo-a-passo)
